# Generated by Django 4.2.15 on 2025-01-15 12:55

import cloudinary.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("child", "0002_alter_child_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(1900, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2025, 1, 15)
                    ),
                ],
                verbose_name="Date of Birth",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="child_picture"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="registration_date",
            field=models.DateField(
                blank=True,
                default=datetime.date(2013, 1, 1),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2013, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2025, 1, 15)
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="year_enrolled",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2013),
                    django.core.validators.MaxValueValidator(2025),
                ],
                verbose_name="The year when the child was enrolled in the program?",
            ),
        ),
        migrations.AlterField(
            model_name="childdepart",
            name="depart_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2013, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2025, 1, 15)
                    ),
                ],
                verbose_name="Departure Date",
            ),
        ),
        migrations.AlterField(
            model_name="childincident",
            name="incident_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2013, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2025, 1, 15)
                    ),
                ],
                verbose_name="Incident Date",
            ),
        ),
    ]
