# Generated by Django 4.2.15 on 2025-03-05 11:36

import apps.child.models
import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("child", "0006_remove_child_picture_alter_childdepart_depart_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childprofilepicture",
            name="picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    apps.child.models.validate_image_size,
                ],
                verbose_name="child_picture",
            ),
        ),
    ]
