# Generated by Django 4.2.15 on 2025-10-15 13:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("child", "0033_alter_childdepart_depart_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childdepart",
            name="depart_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2013, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2025, 10, 15)
                    ),
                ],
                verbose_name="Departure Date",
            ),
        ),
        migrations.AlterField(
            model_name="childincident",
            name="incident_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2013, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2025, 10, 15)
                    ),
                ],
                verbose_name="Incident Date",
            ),
        ),
    ]
