# Generated by Django 4.2.15 on 2026-01-07 21:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("child", "0036_alter_childdepart_depart_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="year_enrolled",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2013),
                    django.core.validators.MaxValueValidator(2026),
                ],
                verbose_name="The year when the child was enrolled in the program?",
            ),
        ),
        migrations.AlterField(
            model_name="childdepart",
            name="depart_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2013, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2026, 1, 8)
                    ),
                ],
                verbose_name="Departure Date",
            ),
        ),
        migrations.AlterField(
            model_name="childincident",
            name="incident_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2013, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2026, 1, 8)
                    ),
                ],
                verbose_name="Incident Date",
            ),
        ),
    ]
