# Generated by Django 4.2.15 on 2026-03-11 16:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("child", "0040_alter_childdepart_depart_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="childprogress",
            name="term",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Term 1", "Term 1"),
                    ("Term 2", "Term 2"),
                    ("Term 3", "Term 3"),
                ],
                max_length=20,
                null=True,
                verbose_name="School Term",
            ),
        ),
        migrations.AddField(
            model_name="childprogress",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Academic Year"
            ),
        ),
        migrations.AlterField(
            model_name="childdepart",
            name="depart_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2013, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2026, 3, 11)
                    ),
                ],
                verbose_name="Departure Date",
            ),
        ),
        migrations.AlterField(
            model_name="childincident",
            name="incident_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2013, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2026, 3, 11)
                    ),
                ],
                verbose_name="Incident Date",
            ),
        ),
    ]
