# Generated by Django 4.2.15 on 2026-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("child", "0041_childprogress_term_childprogress_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childprogress",
            name="previous_schools",
            field=models.TextField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Previous Schools Attended",
            ),
        ),
    ]
