# Generated by Django 4.2.15 on 2025-03-23 16:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_staff_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
