# Generated by Django 4.2.15 on 2025-08-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(
                blank=True,
                default="+12125552368",
                max_length=20,
                null=True,
                verbose_name="Telephone",
            ),
        ),
    ]
