# Generated by Django 4.2.15 on 2024-12-07 19:23

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sponsor", "0001_initial"),
        ("staff", "0001_initial"),
        ("child", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffPayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.date(2018, 1, 1)
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            ),
                        ],
                        verbose_name="Date of payment",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("", "--select month--"),
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        max_length=20,
                        verbose_name="Month of payment",
                    ),
                ),
                (
                    "payment_year",
                    models.IntegerField(default=2018, verbose_name="Year of payment"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                ("is_valid", models.BooleanField(default=False, verbose_name="Valid?")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_payments",
                        to="sponsor.sponsor",
                        verbose_name="Sponsor",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_payments_received",
                        to="staff.staff",
                        verbose_name="Staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Payment",
                "verbose_name_plural": "Staff Payments",
                "db_table": "staff_payments",
            },
        ),
        migrations.CreateModel(
            name="ChildPayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.date(2018, 1, 1)
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            ),
                        ],
                        verbose_name="Date of payment",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("", "--select month--"),
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        max_length=20,
                        verbose_name="Month of payment",
                    ),
                ),
                (
                    "payment_year",
                    models.IntegerField(default=2018, verbose_name="Year of payment"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                ("is_valid", models.BooleanField(default=False, verbose_name="Valid?")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_payments_received",
                        to="child.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_payments",
                        to="sponsor.sponsor",
                        verbose_name="Sponsor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Child Payment",
                "verbose_name_plural": "Child Payments",
                "db_table": "child_payments",
            },
        ),
    ]
