# Generated by Django 4.2.15 on 2025-03-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("child", "0005_alter_childdepart_depart_date_and_more"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childpayments",
            name="child",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_payments_received",
                to="child.child",
                verbose_name="Child",
            ),
        ),
    ]
