# Generated by Django 4.2.15 on 2025-03-04 17:11

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0006_donor"),
        ("finance", "0002_alter_childpayments_child"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.date(2018, 1, 1)
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            ),
                        ],
                        verbose_name="Date of payment",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("", "--select month--"),
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        max_length=20,
                        verbose_name="Month of payment",
                    ),
                ),
                (
                    "payment_year",
                    models.IntegerField(default=2018, verbose_name="Year of payment"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donor_payments",
                        to="sponsor.donor",
                        verbose_name="Donor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donor Payment",
                "verbose_name_plural": "Donor Payments",
                "db_table": "donor_payments",
            },
        ),
    ]
