# Generated by Django 4.2.15 on 2025-03-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_donorpayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donorpayment",
            name="month",
        ),
        migrations.RemoveField(
            model_name="donorpayment",
            name="payment_year",
        ),
    ]
