# Generated by Django 4.2.15 on 2026-05-23 18:17

from django.db import migrations, models
import django.db.models.deletion


def create_default_support_programs(apps, schema_editor):
    SupportProgram = apps.get_model("finance", "SupportProgram")
    programs = (
        ("Child Support", "child_support"),
        ("Child Co-support", "child_co_support"),
        ("Family Support", "family_support"),
        ("Family Co-support", "family_co_support"),
        ("General Support", "general_support"),
        ("Staff Support", "staff_support"),
        ("One-time Donation", "one_time_donation"),
    )
    for name, code in programs:
        SupportProgram.objects.update_or_create(
            code=code,
            defaults={"name": name, "is_active": True},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("child", "0048_alter_childdepart_depart_date_and_more"),
        (
            "sponsor",
            "0047_sponsor_is_child_sponsor_sponsor_is_family_supporter_and_more",
        ),
        ("staff", "0003_alter_staff_picture"),
        ("finance", "0004_remove_donorpayment_month_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("child_support", "Child Support"),
                            ("child_co_support", "Child Co-support"),
                            ("family_support", "Family Support"),
                            ("family_co_support", "Family Co-support"),
                            ("general_support", "General Support"),
                            ("staff_support", "Staff Support"),
                            ("one_time_donation", "One-time Donation"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "support_programs",
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(create_default_support_programs, noop_reverse),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("payment_date", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "source_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unified_payments",
                        to="child.child",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.supportprogram",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sponsor.sponsor",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unified_payments",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-payment_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["sponsor", "program"],
                        name="payments_sponsor_e3aaf7_idx",
                    ),
                    models.Index(
                        fields=["payment_date"], name="payments_payment_aebcb7_idx"
                    ),
                    models.Index(
                        fields=["source_model", "source_id"],
                        name="payments_source__00b417_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("source_model", "source_id"),
                name="unique_legacy_payment_source",
            ),
        ),
    ]
