# Generated by Django 4.2.15 on 2024-12-07 19:23

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reg_number",
                    models.CharField(
                        blank=True,
                        default="G01-001",
                        max_length=10,
                        null=True,
                        verbose_name="Registration ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z]+(?:\\s[A-Za-z]+)*$",
                                "Only letters and spaces are allowed",
                            )
                        ],
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "picture",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="client_uploads",
                    ),
                ),
                (
                    "mobile_telephone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="+256999999999",
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Mobile Telephone",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client Bio Data",
                "verbose_name_plural": "Clients Bio Data",
                "db_table": "client_info",
            },
        ),
    ]
