# Generated by Django 4.2.15 on 2024-12-21 17:01

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SevenHillsRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateField()),
                ("full_name", models.CharField(max_length=255)),
                ("reg_number", models.CharField(max_length=50, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "age_bracket",
                    models.CharField(
                        choices=[
                            ("0-17", "0 – 17"),
                            ("18-25", "18 – 25"),
                            ("26-34", "26 – 34"),
                            ("35-45", "35 – 45"),
                            ("46+", "46 and above"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Widowed", "Widowed"),
                            ("Divorced", "Divorced"),
                            ("Domestic Partnership", "In a Domestic Partnership"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "spouse_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "spouse_contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "number_of_children",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("boys", models.PositiveIntegerField(blank=True, null=True)),
                ("girls", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "children_age_brackets",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("highest_education", models.CharField(max_length=255)),
                ("home_village", models.CharField(max_length=255)),
                ("residence", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "telephone_1",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "telephone_2",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("next_of_kin", models.CharField(max_length=255)),
                (
                    "next_of_kin_telephone_1",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "next_of_kin_telephone_2",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("relationship_with_next_of_kin", models.CharField(max_length=255)),
                ("workplace", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "savings_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "min_savings_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("saving_goal", models.TextField(blank=True, null=True)),
                (
                    "services_interested",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Savings Scheme", "Join Savings Scheme"),
                            ("Skills Training", "Skills Training"),
                            ("Share Group", "Join Share Group"),
                            ("Community Unit", "Join Community Unit"),
                            ("Discipleship", "Discipleship"),
                            ("Volunteering", "Volunteering"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "ministry_groups",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ushering", "Ushering"),
                            ("Evangelism", "Evangelism"),
                            ("Children Ministry", "Children's Ministry"),
                            ("Youth Ministry", "Youth Ministry"),
                            ("Intercession", "Intercession"),
                            ("Choir", "Choir"),
                            ("Hospitality", "Hospitality"),
                            ("Media", "Media"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dc_makerere_association_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1900)],
                    ),
                ),
                (
                    "recommended_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("additional_comments", models.TextField(blank=True, null=True)),
                ("agrees_to_photo_use", models.BooleanField(default=False)),
            ],
        ),
    ]
