# Generated by Django 4.2.15 on 2024-12-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_sevenhillsregistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sevenhillsregistration",
            name="reg_number",
        ),
    ]
