# Generated by Django 4.2.15 on 2025-02-06 06:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_alter_sevenhillsregistration_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sevenhillsregistration",
            name="telephone_1",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
