# Generated by Django 4.2.15 on 2025-02-06 08:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_alter_sevenhillsregistration_telephone_1"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinistryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="sevenhillsregistration",
            name="highest_education",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sevenhillsregistration",
            name="home_village",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="sevenhillsregistration",
            name="ministry_groups",
        ),
        migrations.AlterField(
            model_name="sevenhillsregistration",
            name="next_of_kin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sevenhillsregistration",
            name="next_of_kin_telephone_1",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="sevenhillsregistration",
            name="relationship_with_next_of_kin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sevenhillsregistration",
            name="residence",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="sevenhillsregistration",
            name="services_interested",
        ),
        migrations.AddField(
            model_name="sevenhillsregistration",
            name="ministry_groups",
            field=models.ManyToManyField(blank=True, to="client.ministrygroup"),
        ),
        migrations.AddField(
            model_name="sevenhillsregistration",
            name="services_interested",
            field=models.ManyToManyField(blank=True, to="client.service"),
        ),
    ]
