# Generated by Django 4.2.15 on 2024-12-21 18:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_remove_sevenhillsregistration_reg_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sevenhillsregistration",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(1900, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2024, 12, 21)
                    ),
                ],
                verbose_name="Date of Birth",
            ),
        ),
    ]
