# Generated by Django 4.2.15 on 2025-01-15 12:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_alter_sevenhillsregistration_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sevenhillsregistration",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(1900, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2025, 1, 15)
                    ),
                ],
                verbose_name="Date of Birth",
            ),
        ),
    ]
