# Generated by Django 4.2.15 on 2025-02-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_ministrygroup_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ministrygroup",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
