# Generated by Django 4.2.15 on 2025-02-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0005_alter_ministrygroup_name_alter_service_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sevenhillsregistration",
            name="ministry_groups",
        ),
        migrations.RemoveField(
            model_name="sevenhillsregistration",
            name="services_interested",
        ),
        migrations.DeleteModel(
            name="MinistryGroup",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.AddField(
            model_name="sevenhillsregistration",
            name="ministry_groups",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ushering", "Ushering"),
                    ("Evangelism", "Evangelism"),
                    ("Children Ministry", "Children's Ministry"),
                    ("Youth Ministry", "Youth Ministry"),
                    ("Intercession", "Intercession"),
                    ("Choir", "Choir"),
                    ("Hospitality", "Hospitality"),
                    ("Media", "Media"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sevenhillsregistration",
            name="services_interested",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Savings Scheme", "Join Savings Scheme"),
                    ("Skills Training", "Skills Training"),
                    ("Share Group", "Join Share Group"),
                    ("Community Unit", "Join Community Unit"),
                    ("Discipleship", "Discipleship"),
                    ("Volunteering", "Volunteering"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
