# Generated by Django 4.2.15 on 2025-02-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0006_remove_sevenhillsregistration_ministry_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sevenhillsregistration",
            name="ministry_groups",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sevenhillsregistration",
            name="services_interested",
            field=models.TextField(blank=True, null=True),
        ),
    ]
