# Generated by Django 4.2.15 on 2025-02-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0007_alter_sevenhillsregistration_ministry_groups_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sevenhillsregistration",
            table="seven_hills_registration",
        ),
    ]
