# Generated by Django 4.2.15 on 2025-06-15 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0009_client_email_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True,
                default="no-email@example.com",
                max_length=254,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
                        message="Enter a valid email address.",
                    )
                ],
                verbose_name="Email",
            ),
        ),
    ]
