# Generated by Django 4.2.15 on 2025-06-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0010_client_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
    ]
