# Generated by Django 4.2.15 on 2025-06-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0011_remove_client_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="email_id",
            new_name="email",
        ),
    ]
