# Generated by Django 4.2.15 on 2024-12-07 19:23

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=50, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=6,
                        verbose_name="Gender",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "sponsorship_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "--choose sponsorship type--"),
                            ("Child full support", "Child full support"),
                            ("Child co-support", "Child co-support"),
                            ("Family full support", "Family full support"),
                            ("Family co-support", "Family co-support"),
                            ("General support", "General support"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Sponsorship Type",
                    ),
                ),
                (
                    "expected_amt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Amount Expected(UgX)",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Job Title"
                    ),
                ),
                (
                    "region",
                    models.CharField(max_length=100, null=True, verbose_name="Region"),
                ),
                (
                    "town",
                    models.CharField(max_length=100, null=True, verbose_name="Town"),
                ),
                (
                    "origin",
                    models.CharField(max_length=100, null=True, verbose_name="Origin"),
                ),
                (
                    "business_telephone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="+256999999999",
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Business Telephone",
                    ),
                ),
                (
                    "mobile_telephone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="+256999999999",
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Mobile Telephone",
                    ),
                ),
                (
                    "city",
                    models.CharField(max_length=30, null=True, verbose_name="City"),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.date(2013, 1, 1)
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date(2024, 12, 7)
                            ),
                        ],
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "first_street_address",
                    models.CharField(
                        max_length=100, null=True, verbose_name="First Street Address"
                    ),
                ),
                (
                    "second_street_address",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Second Street Address"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        max_length=50, null=True, verbose_name="ZIP Code or Box Number"
                    ),
                ),
                (
                    "is_departed",
                    models.BooleanField(default=False, verbose_name="Departed?"),
                ),
                (
                    "comment",
                    models.CharField(max_length=100, null=True, verbose_name="Comment"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sponsor_details",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SponsorDeparture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departure_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Departure Date"
                    ),
                ),
                (
                    "departure_reason",
                    models.TextField(verbose_name="Reason for Departure"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="sponsor.sponsor",
                        verbose_name="Sponsor Information",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sponsor Departure",
                "verbose_name_plural": "Sponsor Departures",
            },
        ),
    ]
