# Generated by Django 4.2.15 on 2025-08-09 12:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0022_alter_sponsor_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="start_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2013, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2025, 8, 9)
                    ),
                ],
                verbose_name="Start Date",
            ),
        ),
    ]
