# Generated by Django 4.2.15 on 2025-12-10 16:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0034_alter_sponsor_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="city",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="comment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Comment"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="first_street_address",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="First Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="job_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Job Title"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="origin",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Origin"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Region"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="second_street_address",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Second Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="start_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2013, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2025, 12, 10)
                    ),
                ],
                verbose_name="Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="town",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Town"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="zip_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="ZIP Code or Box Number",
            ),
        ),
    ]
