# Generated by Django 4.2.15 on 2026-05-23 18:17

import datetime
import django.core.validators
from django.db import migrations, models


def backfill_flags_from_sponsorship_type(apps, schema_editor):
    Sponsor = apps.get_model("sponsor", "Sponsor")
    Sponsor.objects.filter(
        sponsorship_type__in=["Child full support", "Child co-support"]
    ).update(is_child_sponsor=True)
    Sponsor.objects.filter(
        sponsorship_type__in=["Family full support", "Family co-support"]
    ).update(is_family_supporter=True)
    Sponsor.objects.filter(sponsorship_type="General support").update(
        is_general_donor=True
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0046_alter_sponsor_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="is_child_sponsor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="is_family_supporter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="is_general_donor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="is_one_time_donor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="is_staff_sponsor",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="start_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2013, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date.today
                    ),
                ],
                verbose_name="Start Date",
            ),
        ),
        migrations.RunPython(backfill_flags_from_sponsorship_type, noop_reverse),
    ]
