# Generated by Django 4.2.15 on 2025-03-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebook",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
