# Generated by Django 4.2.15 on 2026-05-20 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0012_rename_email_id_client_email"),
        ("users", "0002_alter_ebook_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="client",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profile",
                to="client.client",
                verbose_name="Linked Client Account",
            ),
        ),
    ]
