# Generated by Django 4.2.15 on 2026-05-20 20:43

from django.db import migrations, models
import django.db.models.deletion


STAFF_ROLES = {"administrator", "manager", "staff", "boo", "hof", "accountant", "ed"}


def backfill_profile_roles(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    for profile in Profile.objects.all().iterator():
        updates = []
        if profile.client_id:
            profile.account_type = "client"
            profile.staff_role = ""
            updates.extend(["account_type", "staff_role"])
        elif profile.role in STAFF_ROLES:
            profile.account_type = "staff"
            profile.staff_role = profile.role
            updates.extend(["account_type", "staff_role"])
        elif profile.role == "sponsor" or profile.sponsor_id:
            profile.account_type = "sponsor"
            profile.staff_role = ""
            updates.extend(["account_type", "staff_role"])

        if updates:
            profile.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0044_alter_sponsor_start_date"),
        ("users", "0003_profile_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("guest", "Guest / New User"),
                    ("client", "Client"),
                    ("sponsor", "Sponsor"),
                    ("staff", "Staff"),
                ],
                default="guest",
                help_text="Primary workspace this user should enter after login.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="sponsor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profile",
                to="sponsor.sponsor",
                verbose_name="Linked Sponsor Account",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="staff_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No staff role"),
                    ("administrator", "Administrator"),
                    ("manager", "Manager"),
                    ("staff", "General Staff"),
                    ("boo", "Business Operations Officer"),
                    ("hof", "Head of Finance"),
                    ("accountant", "Accountant"),
                    ("ed", "Executive Director"),
                ],
                default="",
                help_text="Only used when account type is Staff.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("administrator", "Administrator"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                    ("guest", "Guest"),
                    ("client", "Client"),
                    ("sponsor", "Sponsor"),
                    ("boo", "Business Operations Officer"),
                    ("hof", "Head of Finance"),
                    ("accountant", "Accountant"),
                    ("ed", "Executive Director"),
                ],
                default="guest",
                max_length=15,
            ),
        ),
        migrations.RunPython(backfill_profile_roles, migrations.RunPython.noop),
    ]
