# Generated by Django 4.2.15 on 2026-05-20

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


CREATE_SAVINGS_TABLES_SQL = """
CREATE TABLE IF NOT EXISTS savings_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number varchar(20) UNIQUE,
    opening_date date NOT NULL,
    status varchar(15) NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL UNIQUE REFERENCES client_info(id) DEFERRABLE INITIALLY DEFERRED,
    created_by_id integer NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS savings_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_type varchar(25) NOT NULL,
    amount numeric(15, 2) NOT NULL,
    transaction_date date NOT NULL,
    payment_method varchar(20) NOT NULL,
    reference varchar(80) NOT NULL,
    notes text NOT NULL,
    status varchar(15) NOT NULL,
    approved_at timestamp with time zone NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    account_id bigint NOT NULL REFERENCES savings_accounts(id) DEFERRABLE INITIALLY DEFERRED,
    approved_by_id integer NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
    recorded_by_id integer NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
    requested_by_id integer NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS savings_status_open_idx
    ON savings_accounts (status, opening_date);
CREATE INDEX IF NOT EXISTS savings_txn_account_status_idx
    ON savings_transactions (account_id, status, transaction_date);
CREATE INDEX IF NOT EXISTS savings_txn_status_date_idx
    ON savings_transactions (status, transaction_date);
CREATE INDEX IF NOT EXISTS savings_accounts_client_id_idx
    ON savings_accounts (client_id);
CREATE INDEX IF NOT EXISTS savings_accounts_created_by_id_idx
    ON savings_accounts (created_by_id);
CREATE INDEX IF NOT EXISTS savings_transactions_account_id_idx
    ON savings_transactions (account_id);
CREATE INDEX IF NOT EXISTS savings_transactions_approved_by_id_idx
    ON savings_transactions (approved_by_id);
CREATE INDEX IF NOT EXISTS savings_transactions_recorded_by_id_idx
    ON savings_transactions (recorded_by_id);
CREATE INDEX IF NOT EXISTS savings_transactions_requested_by_id_idx
    ON savings_transactions (requested_by_id);
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0012_rename_email_id_client_email"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(CREATE_SAVINGS_TABLES_SQL, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="SavingsAccount",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "account_number",
                            models.CharField(blank=True, max_length=20, null=True, unique=True),
                        ),
                        ("opening_date", models.DateField(default=datetime.date.today)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("active", "Active"),
                                    ("dormant", "Dormant"),
                                    ("closed", "Closed"),
                                ],
                                default="active",
                                max_length=15,
                            ),
                        ),
                        ("notes", models.TextField(blank=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "client",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="savings_account",
                                to="client.client",
                            ),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="created_savings_accounts",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "savings_accounts",
                        "ordering": ["client__full_name"],
                    },
                ),
                migrations.CreateModel(
                    name="SavingsTransaction",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "transaction_type",
                            models.CharField(
                                choices=[
                                    ("deposit", "Deposit"),
                                    ("withdrawal", "Withdrawal"),
                                    ("interest", "Interest"),
                                    ("charge", "Charge"),
                                    ("adjustment_credit", "Adjustment Credit"),
                                    ("adjustment_debit", "Adjustment Debit"),
                                ],
                                max_length=25,
                            ),
                        ),
                        ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                        ("transaction_date", models.DateField(default=datetime.date.today)),
                        (
                            "payment_method",
                            models.CharField(
                                choices=[
                                    ("cash", "Cash"),
                                    ("mobile_money", "Mobile Money"),
                                    ("bank_transfer", "Bank Transfer"),
                                    ("cheque", "Cheque"),
                                    ("system", "System"),
                                ],
                                default="cash",
                                max_length=20,
                            ),
                        ),
                        ("reference", models.CharField(blank=True, max_length=80)),
                        ("notes", models.TextField(blank=True)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("pending", "Pending"),
                                    ("approved", "Approved"),
                                    ("rejected", "Rejected"),
                                ],
                                default="approved",
                                max_length=15,
                            ),
                        ),
                        ("approved_at", models.DateTimeField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "account",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="transactions",
                                to="savings.savingsaccount",
                            ),
                        ),
                        (
                            "approved_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="approved_savings_transactions",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "recorded_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="recorded_savings_transactions",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "requested_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="requested_savings_transactions",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "savings_transactions",
                        "ordering": ["-transaction_date", "-created_at"],
                        "indexes": [
                            models.Index(
                                fields=["account", "status", "transaction_date"],
                                name="savings_txn_account_status_idx",
                            ),
                            models.Index(
                                fields=["status", "transaction_date"],
                                name="savings_txn_status_date_idx",
                            ),
                        ],
                    },
                ),
                migrations.AddIndex(
                    model_name="savingsaccount",
                    index=models.Index(fields=["status", "opening_date"], name="savings_status_open_idx"),
                ),
            ],
        ),
    ]
