# Generated by Django 4.2.15 on 2025-02-01 17:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Principal Amount"
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Annual Interest Rate (%)",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "disbursement_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Disbursement Date"
                    ),
                ),
                (
                    "loan_period_months",
                    models.PositiveIntegerField(verbose_name="Loan Period (Months)"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("disbursed", "Disbursed"),
                            ("closed", "Closed"),
                            ("overdue", "Overdue"),
                            ("repaid", "Repaid"),
                            ("rejected", "Rejected"),
                            ("ed_rejected", "ED Rejected"),
                            ("hof_rejected", "HOF Rejected"),
                            ("boo_approved", "BOO Approved"),
                            ("hof_approved", "HOF Approved"),
                            ("ed_approved", "ED Approved"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Current Status",
                    ),
                ),
                (
                    "total_interest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Total Interest Amount",
                    ),
                ),
                (
                    "interest_method",
                    models.CharField(
                        choices=[("flat_rate", "Flat Rate")],
                        default="flat_rate",
                        max_length=20,
                        verbose_name="Interest Calculation Method",
                    ),
                ),
                (
                    "loan_purpose",
                    models.CharField(
                        choices=[
                            ("business", "Business"),
                            ("school_fees", "School Fees"),
                            ("investment", "Investment"),
                        ],
                        default="business",
                        max_length=20,
                        verbose_name="Loan Purpose",
                    ),
                ),
                (
                    "approved_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Approval Date"
                    ),
                ),
                ("reason_for_rejection", models.TextField(blank=True, null=True)),
                (
                    "reason_for_approval",
                    models.TextField(
                        default="Approval granted based on the borrower's ",
                        max_length=100,
                        verbose_name="Reason for Approval",
                    ),
                ),
                (
                    "applied_by_role",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loans",
                        to="loans.chartofaccounts",
                    ),
                ),
                (
                    "applied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by_boo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loans_boo_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="BOO Approved By",
                    ),
                ),
                (
                    "approved_by_ed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loans_ed_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ED Approved By",
                    ),
                ),
                (
                    "approved_by_hof",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loans_hof_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="HOF Approved By",
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="client.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loans_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
                "db_table": "loans",
            },
        ),
    ]
