# Generated by Django 4.2.15 on 2025-03-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_transactionhistory_loanrepayment_loandisbursement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="reason_for_approval",
            field=models.TextField(
                default="Approval granted based on the borrower's ",
                max_length=255,
                verbose_name="Reason for Approval",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="reason_for_rejection",
            field=models.TextField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Reason for Rejection",
            ),
        ),
    ]
