# Generated by Django 4.2.15 on 2025-06-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_alter_loan_reason_for_approval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="loan_purpose",
            field=models.CharField(
                choices=[
                    ("business", "Business"),
                    ("school_fees", "School Fees"),
                    ("investment", "Investment"),
                    ("agriculture", "Agriculture"),
                    ("emergency", "Emergency"),
                    ("personal_development", "Personal Development"),
                    ("salary", "Salary Advance"),
                ],
                default="business",
                max_length=20,
                verbose_name="Loan Purpose",
            ),
        ),
    ]
