# Generated by Django 4.2.15 on 2025-08-22 11:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0005_alter_loan_loan_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrepayment",
            name="penalty_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="Penalty Payment",
            ),
        ),
        migrations.CreateModel(
            name="LoanPenalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "penalty_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Penalty Date"
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Penalty Amount"
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Remaining Penalty Amount",
                    ),
                ),
                (
                    "reason",
                    models.CharField(max_length=255, verbose_name="Penalty Reason"),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Is Paid")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalties",
                        to="loans.chartofaccounts",
                        verbose_name="Penalty Account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="penalties_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalties",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Penalty",
                "verbose_name_plural": "Loan Penalties",
                "db_table": "loan_penalties",
                "ordering": ["-penalty_date"],
            },
        ),
    ]
