# Generated by Django 4.2.15 on 2025-08-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_loanrepayment_penalty_payment_loanpenalty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="reason_for_approval",
            field=models.TextField(
                default="Approval granted based on the borrower's savings history.",
                max_length=255,
                verbose_name="Reason for Approval",
            ),
        ),
    ]
