# Generated by Django 4.2.15 on 2025-08-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0007_alter_loan_reason_for_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="start_date",
            field=models.DateField(verbose_name="Loan Application Date"),
        ),
    ]
