# Generated by Django 4.2.15 on 2026-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0009_loanpenalty_deleted_at_loanpenalty_deleted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="last_reminder_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Reminder Sent"
            ),
        ),
        migrations.AddIndex(
            model_name="loanpenalty",
            index=models.Index(
                fields=["penalty_date", "is_paid"],
                name="loan_penalt_penalty_076861_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loanrepayment",
            index=models.Index(
                fields=["repayment_date"], name="loan_repaym_repayme_fe19d0_idx"
            ),
        ),
    ]
