# Generated by Django 4.2.15 on 2026-03-19 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0012_rename_email_id_client_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0010_loan_last_reminder_sent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="borrower",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="client.client",
            ),
        ),
        migrations.AlterField(
            model_name="loanpenalty",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="penalties_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loanpenalty",
            name="loan",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="penalties",
                to="loans.loan",
            ),
        ),
        migrations.AlterField(
            model_name="loanrepayment",
            name="loan",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repayments",
                to="loans.loan",
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="account",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_history",
                to="loans.chartofaccounts",
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="loan",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="loans.loan",
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["status", "disbursement_date"], name="loan_status_disb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["borrower", "status"], name="loan_borrower_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["due_date", "status"], name="loan_due_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["last_reminder_sent"], name="loan_last_reminder_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanpenalty",
            index=models.Index(
                fields=["loan", "is_paid"], name="penalty_loan_paid_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanrepayment",
            index=models.Index(
                fields=["loan", "repayment_date"], name="repayment_loan_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["loan", "transaction_date"], name="txn_loan_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["account", "transaction_date"], name="txn_account_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["transaction_type", "transaction_date"],
                name="txn_type_date_idx",
            ),
        ),
    ]
