# Generated by Django 4.2.15 on 2026-05-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0011_loan_model_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["status", "loan_purpose"], name="loan_status_purpose_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["applied_by", "status"], name="loan_officer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["start_date", "status"], name="loan_start_status_idx"
            ),
        ),
    ]
