# Generated by Django 4.2.15 on 2026-05-20 08:09

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0012_loan_loan_status_purpose_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("collateral_security", "Collateral / Security"),
                            ("proof_of_income", "Proof of Income"),
                            ("guarantor_form", "Guarantor Form"),
                            ("bank_statement", "Bank Statement"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    cloudinary.models.CloudinaryField(
                        max_length=255,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                ]
                            )
                        ],
                        verbose_name="loan_documents",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="loans.loan",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_loan_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Application Document",
                "verbose_name_plural": "Loan Application Documents",
                "db_table": "loan_application_documents",
                "ordering": ["loan_id", "document_type", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["loan", "document_type"], name="loan_doc_type_idx"
                    ),
                    models.Index(
                        fields=["uploaded_by", "created_at"],
                        name="loan_doc_user_created_idx",
                    ),
                ],
            },
        ),
    ]
