# Generated by Django 4.2.15 on 2024-12-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sponsor", "0001_initial"),
        ("staff", "0001_initial"),
        ("child", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffSponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "--choose sponsorship type--"),
                            ("Child full support", "Child full support"),
                            ("Child co-support", "Child co-support"),
                            ("Family full support", "Family full support"),
                            ("Family co-support", "Family co-support"),
                            ("General support", "General support"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Sponsorship Type",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsored_staff",
                        to="sponsor.sponsor",
                        verbose_name="Sponsor",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsorships_received",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff Sponsorships",
                "db_table": "staff_sponsorship",
                "unique_together": {("staff", "sponsor")},
            },
        ),
        migrations.CreateModel(
            name="ChildSponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "--choose sponsorship type--"),
                            ("Child full support", "Child full support"),
                            ("Child co-support", "Child co-support"),
                            ("Family full support", "Family full support"),
                            ("Family co-support", "Family co-support"),
                            ("General support", "General support"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Sponsorship Type",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsorships_received",
                        to="child.child",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsored_children",
                        to="sponsor.sponsor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Child Sponsorships",
                "db_table": "child_sp_details",
                "unique_together": {("child", "sponsor")},
            },
        ),
    ]
