# Generated by Django 4.2.15 on 2025-08-02 17:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sponsorship", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique internal transaction ID",
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount in the specified currency",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="UGX",
                        help_text="Currency code (e.g., UGX, USD)",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Currency must be one of: UGX, NGN, USD, KES, GHS, ZAR",
                                regex="^(UGX|NGN|USD|KES|GHS|ZAR)$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the payment",
                        max_length=20,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        help_text="Customer's full name",
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Name can only contain letters, numbers, spaces, hyphens, and periods",
                                regex="^[\\w\\s\\-\\.]+$",
                            )
                        ],
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="Customer's email address", max_length=254
                    ),
                ),
                (
                    "transaction_ref",
                    models.CharField(
                        help_text="Unique Flutterwave transaction reference",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "flutterwave_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Flutterwave's transaction ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card", "Card"),
                            ("mobilemoney", "Mobile Money"),
                            ("ussd", "USSD"),
                            ("banktransfer", "Bank Transfer"),
                        ],
                        help_text="Payment method used",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when payment was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last update"
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata from Flutterwave",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated user, if authenticated",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_ref"],
                        name="sponsorship_transac_5c2465_idx",
                    ),
                    models.Index(
                        fields=["status"], name="sponsorship_status_91fb1b_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("transaction_ref",), name="unique_transaction_ref"
            ),
        ),
    ]
