# Generated by Django 4.2.15 on 2025-08-05 19:23

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0002_payment_payment_unique_transaction_ref"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="payment",
            name="unique_transaction_ref",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="sponsorship_transac_5c2465_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="sponsorship_status_91fb1b_idx",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="customer_email",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="flutterwave_transaction_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="meta",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="transaction_ref",
        ),
        migrations.AddField(
            model_name="payment",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="first_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="reference",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
