# Generated by Django 5.2.5 on 2025-09-02 18:27

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0003_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Format: +256xxxxxxxxx", max_length=128, region=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="sponsorship_email_82712f_idx"),
                    models.Index(
                        fields=["phone_number"], name="sponsorship_phone_n_51e935_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email",), name="unique_donor_email"
                    ),
                    models.UniqueConstraint(
                        fields=("phone_number",), name="unique_donor_phone"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1.0)],
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "momo_reference_id",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="sponsorship.donor",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["momo_reference_id"], name="sponsorship_momo_re_c7ac03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["transaction_id"], name="sponsorship_transac_30c14d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.UniqueConstraint(
                fields=("momo_reference_id",), name="unique_momo_reference"
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transaction_id__isnull", False)),
                fields=("transaction_id",),
                name="unique_transaction_id",
            ),
        ),
    ]
