# Generated by Django 5.2.5 on 2025-09-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0004_donor_donation_delete_payment_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="donor",
            name="unique_donor_email",
        ),
        migrations.RemoveIndex(
            model_name="donor",
            name="sponsorship_email_82712f_idx",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="email",
        ),
    ]
