# Generated by Django 4.2.15 on 2025-10-11 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0005_remove_donor_unique_donor_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoMoTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_id", models.CharField(max_length=100, unique=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="UGX", max_length=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESSFUL", "Successful"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payer_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payee_note", models.CharField(blank=True, max_length=255, null=True)),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Donation",
        ),
        migrations.DeleteModel(
            name="Donor",
        ),
    ]
