# Generated by Django 4.2.15 on 2025-10-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0006_momotransaction_delete_donation_delete_donor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="momotransaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="momotransaction",
            name="donor_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="momotransaction",
            name="donor_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
