# Generated by Django 4.2.15 on 2024-12-07 19:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        default="offline",
                        max_length=10,
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("trans_date", models.DateField(verbose_name="Receipt Date")),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("sub_total", models.FloatField(default=0)),
                ("grand_total", models.FloatField(default=0)),
                ("tax_amount", models.FloatField(default=0)),
                ("tax_percentage", models.FloatField(default=0)),
                ("amount_payed", models.FloatField(default=0)),
                ("amount_change", models.FloatField(default=0)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CREDIT_CARD", "Credit Card"),
                            ("DEBIT_CARD", "Debit Card"),
                            ("PAYPAL", "PayPal"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CASH", "Cash"),
                            ("MTN_MOBILE_MONEY", "MTN Mobile Money"),
                            ("AIRTEL_MONEY", "Airtel Money"),
                        ],
                        default="CASH",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "Sales",
            },
        ),
        migrations.CreateModel(
            name="SaleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("total_detail", models.FloatField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "db_table": "SaleDetails",
            },
        ),
    ]
