# Generated by Django 4.2.15 on 2026-05-22 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productvariant_stockmovement"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saledetail",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_details",
                to="products.productvariant",
            ),
        ),
    ]
