# Generated by Django 4.2.15 on 2026-05-22 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Variant Name")),
                (
                    "sku",
                    models.CharField(max_length=64, unique=True, verbose_name="SKU"),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=64, verbose_name="Barcode"),
                ),
                (
                    "option_value",
                    models.CharField(
                        blank=True,
                        help_text="Example: Small, Blue, 500ml, Pack of 12.",
                        max_length=120,
                        verbose_name="Option Value",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cost Price",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Selling Price",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stock Quantity"
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Low Stock Threshold"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("", "-- Choose status --"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Variant"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "db_table": "product_variant",
                "ordering": ["product__name", "name"],
                "unique_together": {("product", "name")},
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "Stock In"),
                            ("OUT", "Stock Out"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("SALE", "Sale"),
                            ("RETURN", "Return"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity Change")),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="products.productvariant",
                        verbose_name="Variant",
                    ),
                ),
            ],
            options={
                "db_table": "stock_movement",
                "ordering": ["-created_at"],
            },
        ),
    ]
