name: Send Loan Notifications

on:
  schedule:
    - cron: "0 5 * * 1,4" # Monday & Thursday at 5 UTC = 8 AM EAT
  workflow_dispatch:

jobs:
  send_loan_notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Loan Notifications Command
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BOO_EMAIL: ${{ secrets.BOO_EMAIL }}
          HOF_EMAIL: ${{ secrets.HOF_EMAIL }}
          PROGS_ADMIN_EMAIL: ${{ secrets.PROGS_ADMIN_EMAIL }}
        run: python manage.py send_loan_notifications
